version: "3"
services:
  db:
    image: postgres:10.4
    ports:
      - "5432:5432"

  django:
    hostname: django
    env_file:
      - docker/dev/docker.env
    build:
      context: ./
      dockerfile: docker/dev/django/Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - db

    volumes:
      - .:/code

  worker:
    env_file:
      - docker/dev/docker.env
    build:
      context: ./
      dockerfile: docker/dev/worker/Dockerfile
    depends_on:
      - django
    volumes:
      - .:/code

  nodejs:
    hostname: nodejs
    build:
      context: ./
      dockerfile: docker/dev/nodejs/Dockerfile
    environment:
      NODE_ENV: development
    ports:
      - "8888:8888"
      - "35729:35729"
    volumes:
      - .:/code
      - /code/node_modules
      - /code/bower_components

  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"

  nginx:
    image: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      


