# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-24 21:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("challenges", "0047_add_model_to_invite_user_in_challenge")
    ]

    operations = [
        migrations.AddField(
            model_name="challenge",
            name="use_host_credentials",
            field=models.BooleanField(default=False),
        ),
    ]
